steps:
  # Download and extract source
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://{{BUCKET_NAME}}/{{ARCHIVE_NAME}}', '/workspace/source.zip']

  - name: 'ubuntu'
    args: ['unzip', '/workspace/source.zip', '-d', '/workspace/src']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '{{IMAGE_URI}}'
      - '-t'
      - '{{IMAGE_URI_WITH_BUILD_ID}}'
      - '-f'
      - '/workspace/src/{{DOCKERFILE}}'
{{BUILD_ARGS}}
      - '/workspace/src'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '{{IMAGE_URI}}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '{{IMAGE_URI_WITH_BUILD_ID}}']

options:
  machineType: '{{MACHINE_TYPE}}'
  logging: CLOUD_LOGGING_ONLY
timeout: '{{TIMEOUT}}'
